// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvubliqvuqkjlpeolhpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2dWJsaXF2dXFramxwZW9saHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2ODQ3NTAsImV4cCI6MjA3ODI2MDc1MH0.rgq99ev55ujMJoS03tBWKLG6-gqYzNnxpYCpsqB-Tio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});